---
title: "The Factors of CO2 Emission"
author: 
  - Uzer, Ufuk[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080504, [Github Repo](https://github.com/ufukuzer/Midterm)




# Introduction

Recent increase in CO2 emissions, the governments are focusing on the causes and the relations of CO2 emission more than ever. Therefore, if the states understand the facts and figures of the CO2 emission, they are able to take precautions for next generations.

Due to the reasons above,this project is focusing on the CO2 emissions and their relations with populations, GDP (Gross Domestic Products) per capita, and forest area. Taking the 2019 data from worldbank.com is going to give us real world relations.

My expectation from the analysis is that i will find a relation with CO2 emission and the data set listed in above and how much is going to have an impact on CO2 emission. Then, if i cannot find any relations with CO2 emission with the data set. I will change the data with impact of technological progress or the increase of the number of the cars.

## Literature Review

In literature review, the cited articles are going to be analyzed more deeply. 

 [@xu2020investigating; @waheed2018forest; @wang2019examining ; @begum2015co2].




\newpage
# References {#references}
<div id="refs"></div>

